version: "3.9"

services:
  frontend:
    build: .
    container_name: "frontend"
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - "db"
    environment:
      env_file: .env
  backend:
    container_name: "backend"
    restart: unless-stopped
    build: ../metarbackend
    ports:
      - 5000:5000
  db:
    image: postgres
    container_name: "db"
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=metar
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
